apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: assurancesproject
  annotations:
    github.com/project-slug: ounissighofrane/assurancesproject
spec:
  type: service
  lifecycle: unknown
  owner: group:guests
